### PR TITLE
fix: cross account catalog_id glue client function calls

### PR DESCRIPTION
**Pull request by brunofaustino**
### Description

Using [Athena with Glue in cross-account](https://docs.aws.amazon.com/athena/latest/ug/security-iam-cross-account-glue-catalog-access.html) environments results in the error bellow:

CleanShot 2023-08-11 at 12 12 51@2x

**Context**: Currently, I'm using the Athena service within an AWS account (Account A) to query data hosted in a Glue Catalog situated in another AWS account (Account B). The glue client typically infers this information from the active account's ID. However, I have identified an error that occurs due to an account ID parameter that needs adjustment to reflect the account ID where the tables reside (Account B, in this case).

In this scenario, it is advisable to provide the catalog_id when invoking the Glue client function.

## Checklist
- [ ] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [ ] You kept your Pull Request small and focused on a single feature or bug fix.
- [ ] You added unit testing when necessary
- [ ] You added functional testing when necessary

### CODE REVIEW

**Comment by brunofaustino** [comment]
I've noticed potentially redundant sections due to the repeated calls to:

```
data_catalog = self._get_data_catalog(relation.database)
catalog_id = get_catalog_id(data_catalog)
```

 I'm not familiar with the detailed structure of DBT's objects and classes. I'm uncertain whether it's feasible to directly incorporate catalog_id as an attribute of the Relation. This would potentially enable a streamlined approach like (`glue_client.get_table(CatalogId=relation.catalog_id, ...)`. Are there any recommendations for enhancing this approach?

**Comment by nicor88** [comment]
@brunofaustino I've a similar setup - I use account B (consumer) to query data from a table in account A (producer) - and all works fine for me. Did you create a resource link for your database in lakeformation?

**Comment by brunofaustino** [comment]
I'm write and read tables in account A (producer), performing these operations through account B (consumer).
Therefore, no table is written directly to account B (consumer).

Due to specific characteristics of the project I'm working on, I'm not using Lakeformation (where I would use use _resource link_).
Instead, I'm leveraging [Athena's cross-account AWS Glue catalog feature](https://docs.aws.amazon.com/athena/latest/ug/security-iam-cross-account-glue-catalog-access.html) to register the pre-existing AWS Glue catalog in account A within the environment of account B. By doing so, we register the catalog (from account A) as an [Athena DataCatalog resource](https://docs.aws.amazon.com/athena/latest/APIReference/API_DataCatalog.html) within account B (consumer). 

As a result, we use Athena in account B (consumer) to register the catalog that originates from account A (producer), thereby enabling Athena to execute cross-account queries.

In this scenario, the execution of dbt-athena fails when calling the `glue_client.get_table` function, requiring the CatalogId parameter to be provided.

**Comment by brunofaustino** [comment]
@nicor88 I'm write and read tables in account A (producer), performing these operations through account B (consumer).
Therefore, no table is written directly to account B (consumer).

Due to specific characteristics of the project I'm working on, I'm not using Lakeformation (where I would use use _resource link_).
Instead, I'm leveraging [Athena's cross-account AWS Glue catalog feature](https://docs.aws.amazon.com/athena/latest/ug/security-iam-cross-account-glue-catalog-access.html) to register the pre-existing AWS Glue catalog in account A within the environment of account B. By doing so, we register the catalog (from account A) as an [Athena DataCatalog resource](https://docs.aws.amazon.com/athena/latest/APIReference/API_DataCatalog.html) within account B (consumer). 

As a result, we use Athena in account B (consumer) to register the catalog that originates from account A (producer), thereby enabling Athena to execute cross-account queries.

In this scenario, the execution of dbt-athena fails when calling the `glue_client.get_table` function, requiring the CatalogId parameter to be provided.

**Comment by nicor88** [comment]
@brunofaustino thanks. I believe that your implementation should work, please fix the CI.

**Comment by brunofaustino** [comment]
@nicor88 
I checked that the pipeline now is failing with "`An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.`".

Could you please validate this?

**Comment by nicor88** [comment]
@brunofaustino the issue is most probably due to the fact that the mock calls on aws are not mocked as they should - therefore the unit tests must be re-adapted I believe.

**Comment by nicor88** [comment]
@svdimchenko @Jrmyy do you want to have another look?

**Review by svdimchenko — APPROVED** [review]

**Comment by nicor88** [comment]
I tried this PR with the setup that I currently use, where I access cross account tables via resource links and lakeformation sharing - all still worked good.

**Review by nicor88 — APPROVED** [review]

**Pull request merged**
