### PR TITLE
feat: add nested data types support for Athena get_columns_in_relation macro

### PR DESCRIPTION
**Pull request by svdimchenko**
### Description

I’m facing the problem with incremental materialization for iceberg  tables. Macro athena__get_columns_in_relation is currently getting fields types from information_schema . However there are some problems:
nested fields are stored as row(field type) instead of struct<field: type>
fields with type binary are stored as ``varbinary``.

You can test it with following table:
```
CREATE EXTERNAL TABLE `test.nested` 
  `actor_ip` string,
  `sms` string ,
  `metadata` struct<region:string,macro_region:string,override_by:string,timestamp:bigint>, 
  `profile` struct<email:string,phone:string,regions:struct<region:string,timestamp:bigint>,last_name:string,first_name:string,living_address:struct<city:string,country:string>,is_short_registration:boolean> ,
`source_values` struct<regions:struct<region:string,timestamp:bigint,override_by:string>>
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  's3://REPLACE_ME/'
```

## Checklist
- [x] You followed [contributing section](https://github.com/dbt-athena/dbt-athena#contributing)
- [x] You added unit testing when necessary
- [x] You added functional testing when necessary

### CODE REVIEW

**Comment by nicor88** [comment]
@svdimchenko have a look at https://www.conventionalcommits.org/en/v1.0.0/ and adapt the PR title accordingly.

**Comment by nicor88** [comment]
@svdimchenko Will be nice if you can provide the models that you use to test this out, e.g. with some mock data. This will help the reviewers.

**Comment by nicor88** [comment]
@svdimchenko the proposed test model doesn't help me. Could you add a dbt model with mock data to help us to fully test this?

**Comment by nicor88** [comment]
@mattiamatrix shall we merge this?

**Comment by Jrmyy** [comment]
What I don't understand is that we already have a utils macro that gets correct type based on information schema or maybe I am missing something ? 🤔

**Comment by nicor88** [comment]
I think that indeed in here we could aim to use the `data_type` macro, as it should render the right data type.

**Comment by nicor88** [comment]
@svdimchenko this PR needs to be re-adapted. In https://github.com/dbt-athena/dbt-athena/pull/174 we replace the get_columns method with a glue api col, therefore we don't use the information schema from athena/trino anymore.

Could you check if this feature is still relevant for your use case? or if the issue is solved using the latest version (main)??

cc @Jrmyy

**Comment by svdimchenko** [comment]
not more actual

**Pull request closed without merging**
